# Generated by Django 3.0.7 on 2020-06-20 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('object_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Offer', verbose_name='Объект голосования')),
                ('user_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Голосующий')),
            ],
            options={
                'verbose_name': 'Голос (предложения)',
                'verbose_name_plural': 'Голоса (предложения)',
                'unique_together': {('user_vote', 'object_vote')},
            },
        ),
    ]
