# Generated by Django 3.0.7 on 2020-06-20 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория (предложений)',
                'verbose_name_plural': 'Категории (предложений)',
            },
        ),
        migrations.CreateModel(
            name='TagOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег (предложений)',
                'verbose_name_plural': 'Теги (предложений)',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('idea_short', models.CharField(max_length=255, verbose_name='Краткое описание (идея проекта)')),
                ('idea', models.TextField(verbose_name='Подробное описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='offers.CategoryOffer', verbose_name='Категория')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='offers.TagOffer', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Прдложение',
                'verbose_name_plural': 'Прдложения',
            },
        ),
    ]
