# Generated by Django 3.0.7 on 2020-06-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(to='reference.Tag', verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
